# Generated by Django 3.0.6 on 2020-05-30 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_django'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
