# Generated by Django 3.0.6 on 2020-05-30 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20200530_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='id_category',
            field=models.ForeignKey(db_column='id_category', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='mysite.Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.CharField(max_length=100),
        ),
    ]
