# Generated by Django 3.0.6 on 2020-06-01 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_auto_20200601_2315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='id_category',
            new_name='id_category_id',
        ),
    ]
