# Generated by Django 3.0.6 on 2020-06-01 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_auto_20200601_2353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='id_category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='id_category_id',
            new_name='id',
        ),
    ]
